/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CalAPP.view.MyContainer', {
    extend: 'Ext.Container',

    requires: [
        'Ext.field.Text',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        height: '100%',
        width: '100%',
        layout: 'fit',
        items: [
            {
                xtype: 'textfield',
                docked: 'top',
                label: 'To'
            },
            {
                xtype: 'container',
                html: '<div id="tymca" ></div>',
                itemId: 'tinyMCAEditor',
                width: '100%',
                listeners: [
                    {
                        fn: function(element, eOpts) {
                            tinymce.init({
                                selector: '#tymca',
                                //height: 500,
                                theme: 'modern',
                                plugins: [
                                'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                                'searchreplace wordcount visualblocks visualchars code fullscreen',
                                'insertdatetime media nonbreaking save table contextmenu directionality',
                                'emoticons template paste textcolor colorpicker textpattern imagetools'
                                ],
                                toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
                                toolbar2: 'print preview media | forecolor backcolor emoticons',
                                image_advtab: true,
                                templates: [
                                { title: 'Test template 1', content: 'Test 1' },
                                { title: 'Test template 2', content: 'Test 2' }
                                ],
                                content_css: [
                                '//fast.fonts.net/cssapi/e6dc9b99-64fe-4292-ad98-6974f93cd2a2.css',
                                '//www.tinymce.com/css/codepen.min.css'
                                ]
                            });

                        },
                        event: 'painted'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            this.up('#navigationView').pop();

                        },
                        text: 'Schedule'
                    }
                ]
            }
        ]
    },

    initialize: function() {
        // tinymce.init({
        //   selector: '#tymca',




        this.callParent();
    }

});